language: ruby
rvm:
#  - "1.8.7"
#  - "1.9.2"
  - "1.9.3"
#  - jruby-18mode # JRuby in 1.8 mode
#  - jruby-19mode # JRuby in 1.9 mode
#  - rbx

before_script:
  - cd sample_app
  - bundle install
  - npm install
  - bower install
before_install:
  - "export DISPLAY=:99.0" #for GUI test
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# uncomment this line if your project needs to run something other than `rake`:
#script: bundle exec rspec spec:models
script: karma start --browsers PhantomJS --single-run #bundle exec rake spec:models
#script: "./testscript.sh" #future script commented for now

#- RAILS_ENV=test bundle exec rake --trace db:migrate test
#- karma start --single-run --browsers PhantomJS test/karma/config/unit.js