language: ruby
rvm:
#  - "1.8.7"
#  - "1.9.2"
  - "1.9.3"
env:
  - GH_TOKEN=052a204f8df159b9a8646327929d530c881532ff

notifications:
  email:
    - rafal@pkey.pl

before_script:
  - cd sample_app
  - bundle install
#  - npm install
#  - bower install
before_install:
#  - "export DISPLAY=:99.0" #for GUI test
#  - "sh -e /etc/init.d/xvfb start"
#  - sleep 3 # give xvfb some time to start

script:
#  - bundle exec rake spec:lib
#  - bundle exec rake spec:models
#  - karma start --browsers PhantomJS --single-run
#script: "./testscript.sh" #future script commented for now
  - rake about

after_success: ./after_success.sh