# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure('2') do |config|
  config.vm.box      = 'precise32'
  config.vm.box_url  = 'http://files.vagrantup.com/precise32.box'
  config.vm.hostname = 'rafolo-rails-2.1-devbox'
  #config.vm.network "private_network", ip: "192.168.2.49", virtualbox__intnet: true
  config.vm.network :public_network, ip: "192.168.2.48"

  config.vm.provider 'vmware_fusion' do |v, override|
    override.vm.box     = 'precise64'
    override.vm.box_url = 'http://files.vagrantup.com/precise64_vmware.box'
  end

  config.vm.provider 'parallels' do |v, override|
    override.vm.box = 'parallels/ubuntu-12.04'
    override.vm.box_url = 'https://vagrantcloud.com/parallels/ubuntu-12.04'

    # Can be running at background, see https://github.com/Parallels/vagrant-parallels/issues/39
    v.customize ['set', :id, '--on-window-close', 'keep-running']
  end


  #config.vm.network "public_network"
  #config.vm.network :public_network, ip: "192.168.2.49"
  config.vm.network :forwarded_port, guest: 3000, host: 3000 #ruby web
  config.vm.network :forwarded_port, guest: 5900, host: 5900 #vnc

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = 'puppet/manifests'
    puppet.module_path    = 'puppet/modules'
  end
end
