common: &common
  app_title: Vasabi

development:
  <<: *common
  landscape_title: dev
test:
  <<: *common
  landscape_title: test
production:
  <<: *common
  landscape_title: ...
beta:
  <<: *common
  landscape_title: beta
staging:
  <<: *common
  landscape_title: staging
staging-s1:
  <<: *common
  landscape_title: staging-s1