source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'bcrypt-ruby', '3.0.1'
gem 'faker', '1.0.1'
gem 'will_paginate', '3.0.5'

group :development, :test do
  gem 'sqlite3', '1.3.5'
  gem 'rspec-rails', '2.9.0'
  gem 'guard-rspec', '0.5.5'
  gem 'test-unit', '~> 2.5.5'
  gem 'annotate', '~> 2.6.3'
  gem 'autorefresh', '~>1.0.0'
  gem 'watchr', '~> 0.7'
  gem 'webrick', '~> 1.3.1'
end

# Gems used only for assets and not required
# in production environments by default.
group(:assets) {
  gem 'bootstrap-sass', '3.1.1.1'
  gem 'sass-rails', '3.2.6'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '2.5.0'

  gem 'ngannotate-rails'
}

group :test do
  gem 'capybara', '1.1.2'
  gem 'factory_girl_rails', '1.4.0'
  gem 'cucumber-rails', '1.2.1', require: false
  gem 'database_cleaner', '0.7.0'
  gem 'rb-fsevent', '>=0.4.3.1', :require => false
  gem 'growl', '1.0.3'
  gem 'guard-spork', '0.3.2'  
  gem 'spork', '0.9.0'
  gem 'launchy', '2.1.0'
end

group :production do
  #gem 'sqlite3', '1.3.5'
  gem 'pg', '0.12.2'
  gem 'rails_12factor'
  gem 'autorefresh', '~>1.0.0'
end

group :beta do
  gem 'sqlite3', '1.3.5'
  gem 'rails_12factor'
  gem 'autorefresh', '~>1.0.0'

  gem 'uglifier', '2.5.0'
end